#Kubernetes manifest for wordpress

apiVersion: v1
kind: Service
metadata: 
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wordpress
          hostPath:
            path: /srv/k8s-volumes/wordpress
      containers:
      - name: wordpress
        image: wordpress:5.3.0
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql:3306
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: password
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_CONFIG_EXTRA
          value: >
            define('FS_METHOD','direct');
        volumeMounts:
          - name: wordpress
            mountPath: /var/www/html/wp-content
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress
spec:
  rules:
  - host: mywordpressapptest.lab
    http:
      paths:
      - backend:
          service.name: wordpress
          service.port.number: 80

